language: java
os:
  - linux
branches:
  only:
    - master
before_script:
  - chmod +x mvnw
script:
  - ./mvnw clean install
  - ./mvnw test
after_success:
  - bash <(curl -s https://codecov.io/bash)
